# Generated by Django 3.2.16 on 2025-04-25 05:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='VN', max_length=50)),
                ('currency', models.CharField(default='VND', max_length=50)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('close', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritiesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('open', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('high', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('low', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('close', models.DecimalField(decimal_places=2, max_digits=16)),
                ('adjusted_close', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('volume', models.BigIntegerField(default=0)),
                ('securities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.securities')),
            ],
        ),
        migrations.AddConstraint(
            model_name='securitiesprice',
            constraint=models.UniqueConstraint(fields=('securities', 'date'), name='unique_securities_date'),
        ),
        migrations.AddIndex(
            model_name='securities',
            index=models.Index(fields=['user', 'code'], name='securities__user_id_13ccdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='securities',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='unique_user_code'),
        ),
    ]
