# Generated by Django 3.2.16 on 2025-04-17 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('exchange', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Vietnam', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
