# Generated by Django 3.2.16 on 2025-04-23 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20250417_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('about_me', models.TextField()),
                ('finhub_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('alpha_vantage_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_source_1_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_source_2_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_source_3_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('user', 'ticker')},
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['user', 'ticker'], name='home_stock_user_id_7366c8_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('stock', 'date')},
        ),
    ]
