# Generated by Django 3.2.16 on 2025-04-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20250423_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stock_source_1_api_key',
            new_name='eodhd_api_key',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='stock_source_2_api_key',
            new_name='google_map_api_key',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='stock_source_3_api_key',
            new_name='yahoo_finance_api_key',
        ),
    ]
