# Generated by Django 3.2.16 on 2025-04-24 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20250424_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='close',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stock',
            name='close_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='VND', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='isin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='country',
            field=models.CharField(default='VN', max_length=50),
        ),
    ]
