# Generated by Django 3.2.16 on 2025-04-25 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20250424_0939'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='unique_user_ticker',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='home_stock_user_id_7366c8_idx',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='code',
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='adjusted_close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='open',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['user', 'code'], name='home_stock_user_id_52abb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='unique_user_code'),
        ),
        migrations.AddConstraint(
            model_name='stockprice',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_date'),
        ),
    ]
