# Generated by Django 3.2.16 on 2025-04-25 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20250425_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='close_date',
            new_name='date',
        ),
    ]
